package net.ekotsk.misc;

import dev.architectury.registry.CreativeTabRegistry;
import dev.architectury.registry.registries.DeferredRegister;
import dev.architectury.registry.registries.RegistrySupplier;
import net.ekotsk.ASOIAFMod;
import net.ekotsk.item.ModItems;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.CreativeModeTabs;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;

import java.util.function.Supplier;

import static com.magistuarmory.misc.ModCreativeTabs.append;
import static com.magistuarmory.misc.ModCreativeTabs.createTab;
import static dev.architectury.registry.CreativeTabRegistry.appendStack;

public class ModCreativeTabs {
    static final DeferredRegister<CreativeModeTab> TABS = DeferredRegister.create(ASOIAFMod.MOD_ID, Registries.CREATIVE_MODE_TAB);
    static final RegistrySupplier<CreativeModeTab> ASOIAF_WEAPONS = createTab("asoiaf_weapons", ModItems.ICE);
    static final RegistrySupplier<CreativeModeTab> ASOIAF_ARMOR = createTab("asoiaf_armor", ModItems.LANNISTER_HELMET);
    public static final ResourceKey<CreativeModeTab> INGRIDIENTS_RESOURCE_KEY = CreativeModeTabs.INGREDIENTS;
    public static final ResourceKey<CreativeModeTab> NATURAL_RESOURCE_KEY = CreativeModeTabs.NATURAL_BLOCKS;
    public static final ResourceKey<CreativeModeTab> BUILDING_RESOURCE_KEY = CreativeModeTabs.BUILDING_BLOCKS;
    public static final ResourceKey<CreativeModeTab> FUNC_RESOURCE_KEY = CreativeModeTabs.FUNCTIONAL_BLOCKS;


    public static void init() {
        TABS.register();
        append(ASOIAF_WEAPONS, ModItems.AEGON_DAGGER);
        append(ASOIAF_WEAPONS, ModItems.BLACKFYRE);
        append(ASOIAF_WEAPONS, ModItems.DARK_SISTER);
        append(ASOIAF_WEAPONS, ModItems.ICE);
        append(ASOIAF_WEAPONS, ModItems.CRAB_PINCER);
        append(ASOIAF_WEAPONS, ModItems.DAWN);
        append(ASOIAF_WEAPONS, ModItems.LAMENTATION);
        append(ASOIAF_WEAPONS, ModItems.LONGCLAW);
        append(ASOIAF_WEAPONS, ModItems.NIGHTFALL);
        append(ASOIAF_WEAPONS, ModItems.BRIGHTROAR);
        append(ASOIAF_WEAPONS, ModItems.ORPHANMAKER);
        append(ASOIAF_WEAPONS, ModItems.RED_RAIN);
        append(ASOIAF_WEAPONS, ModItems.ROBERT_HAMMER);
        append(ASOIAF_WEAPONS, ModItems.TRUTH);
        append(ASOIAF_WEAPONS, ModItems.VIGILANCE);
        append(ASOIAF_WEAPONS, ModItems.LADY_FORLORN);
        append(ASOIAF_WEAPONS, ModItems.HEARTSBANE);
        append(ASOIAF_WEAPONS, ModItems.SANDOQ);
        append(ASOIAF_WEAPONS, ModItems.WEIRWOOD_LONGBOW);
        append(ASOIAF_WEAPONS, ModItems.WEIRWOOD_ARROW);

        append(ASOIAF_ARMOR, ModItems.LANNISTER_HELMET);
        appendStack(ASOIAF_ARMOR, LANNISTER_CHESTPLATE_SUPPLIER);
        append(ASOIAF_ARMOR, ModItems.LANNISTER_LEGGINGS);
        append(ASOIAF_ARMOR, ModItems.FANCY_BOOTS);
        append(ASOIAF_ARMOR, ModItems.LANNISTER_LORD_HELMET);
        appendStack(ASOIAF_ARMOR, LANNISTER_LORD_CHESTPLATE_SUPPLIER);
        append(ASOIAF_ARMOR, ModItems.LANNISTER_LORD_LEGGINGS);
        append(ASOIAF_ARMOR, ModItems.VALYRIAN_STEEL_HELMET);
        append(ASOIAF_ARMOR, ModItems.VALYRIAN_STEEL_CHESTPLATE);
        append(ASOIAF_ARMOR, ModItems.VALYRIAN_STEEL_LEGGINGS);
        append(ASOIAF_ARMOR, ModItems.VALYRIAN_STEEL_BOOTS);
        append(ASOIAF_ARMOR, ModItems.NIGHT_WATCH_HAT);
        append(ASOIAF_ARMOR, ModItems.NIGHT_WATCH_CHESTPLATE);
        append(ASOIAF_ARMOR, ModItems.NIGHT_WATCH_LEGGINGS);
        append(ASOIAF_ARMOR, ModItems.NIGHT_WATCH_BOOTS);
        append(ASOIAF_ARMOR, ModItems.NORTHERN_HELMET);
        append(ASOIAF_ARMOR, ModItems.NORTHERN_CHESTPLATE);
        append(ASOIAF_ARMOR, ModItems.NORTHERN_LEGGINGS);
        append(ASOIAF_ARMOR, ModItems.NORTHERN_BOOTS);
        append(ASOIAF_ARMOR, ModItems.GOLD_CLOAK_HELMET);
        append(ASOIAF_ARMOR, ModItems.GOLD_CLOAK_CHESTPLATE);
        append(ASOIAF_ARMOR, ModItems.GOLD_CLOAK_LEGGINGS);
        append(ASOIAF_ARMOR, ModItems.GOLD_CLOAK_BOOTS);
        append(ASOIAF_ARMOR, ModItems.KOTSK_GOLD_CLOAK_HELMET);
        append(ASOIAF_ARMOR, ModItems.KOTSK_GOLD_CLOAK_CHESTPLATE);
        append(ASOIAF_ARMOR, ModItems.KOTSK_GOLD_CLOAK_LEGGINGS);
        append(ASOIAF_ARMOR, ModItems.KOTSK_GOLD_CLOAK_BOOTS);
        append(ASOIAF_ARMOR, ModItems.GOT_GOLD_CLOAK_HELMET);
        append(ASOIAF_ARMOR, ModItems.GOT_GOLD_CLOAK_CHESTPLATE);
        append(ASOIAF_ARMOR, ModItems.GOT_GOLD_CLOAK_LEGGINGS);
        append(ASOIAF_ARMOR, ModItems.HOTD_KINGSGUARD_HELMET);
        append(ASOIAF_ARMOR, ModItems.HOTD_KINGSGUARD_CHESTPLATE);
        append(ASOIAF_ARMOR, ModItems.HOTD_KINGSGUARD_LEGGINGS);
        append(ASOIAF_ARMOR, ModItems.HOTD_KINGSGUARD_BOOTS);
        append(ASOIAF_ARMOR, ModItems.KOTSK_KINGSGUARD_HELMET);
        append(ASOIAF_ARMOR, ModItems.KOTSK_KINGSGUARD_CHESTPLATE);
        append(ASOIAF_ARMOR, ModItems.KOTSK_KINGSGUARD_LEGGINGS);
        append(ASOIAF_ARMOR, ModItems.KOTSK_KINGSGUARD_BOOTS);
        append(ASOIAF_ARMOR, ModItems.KINGSGUARD_HELMET);
        append(ASOIAF_ARMOR, ModItems.KINGSGUARD_CHESTPLATE);
        append(ASOIAF_ARMOR, ModItems.KINGSGUARD_LEGGINGS);
        append(ASOIAF_ARMOR, ModItems.KINGSGUARD_BOOTS);
        append(ASOIAF_ARMOR, ModItems.KINGSGUARD_2_HELMET);
        append(ASOIAF_ARMOR, ModItems.KINGSGUARD_2_CHESTPLATE);
        append(ASOIAF_ARMOR, ModItems.KINGSGUARD_2_LEGGINGS);
        append(ASOIAF_ARMOR, ModItems.KINGSGUARD_2_BOOTS);
        append(ASOIAF_ARMOR, ModItems.GREYJOY_HELMET);
        append(ASOIAF_ARMOR, ModItems.GREYJOY_CHESTPLATE);
        append(ASOIAF_ARMOR, ModItems.GREYJOY_LEGGINGS);
        append(ASOIAF_ARMOR, ModItems.GREYJOY_BOOTS);
        append(ASOIAF_ARMOR, ModItems.DORNISH_HELMET);
        append(ASOIAF_ARMOR, ModItems.DORNISH_CHESTPLATE);
        append(ASOIAF_ARMOR, ModItems.DORNISH_LEGGINGS);
        append(ASOIAF_ARMOR, ModItems.DORNISH_BOOTS);

        append(ASOIAF_ARMOR, ModItems.HAND_SIGN_DECORATION);
        append(ASOIAF_ARMOR, ModItems.FANCY_CAPE_DECORATION);
        append(ASOIAF_ARMOR, ModItems.NIGHT_WATCH_CAPE_DECORATION);
        append(ASOIAF_ARMOR, ModItems.GOLD_CLOAK_LEFT_DECORATION);
        append(ASOIAF_ARMOR, ModItems.GOLD_CLOAK_RIGHT_DECORATION);
        append(ASOIAF_ARMOR, ModItems.AEGON_CROWN_DECORATION);
        append(ASOIAF_ARMOR, ModItems.HOTD_AEGON_CROWN_DECORATION);
        append(ASOIAF_ARMOR, ModItems.JAEHAERYS_CROWN_DECORATION);
        append(ASOIAF_ARMOR, ModItems.HOTD_JAEHAERYS_CROWN_DECORATION);
        append(ASOIAF_ARMOR, ModItems.AEGON_DRAGONSBANE_CROWN_DECORATION);
        append(ASOIAF_ARMOR, ModItems.AEGON_UNWORTHY_CROWN_DECORATION);
        append(ASOIAF_ARMOR, ModItems.MAEKAR_CROWN_DECORATION);
        append(ASOIAF_ARMOR, ModItems.ROBERT_CROWN_DECORATION);
        append(ASOIAF_ARMOR, ModItems.HIGH_SEPTON_CROWN);
        append(ASOIAF_ARMOR, ModItems.DRAGON_DECORATION);

        append(INGRIDIENTS_RESOURCE_KEY, ModItems.SPEAR_PATTERN);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.DORNISH_SUN_PATTERN);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.BRIGHT_SUN_PATTERN);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.SUNS_PATTERN);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.MOONS_PATTERN);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.STARK_PATTERN);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.KRAKEN_PATTERN);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.LANNISTER_PATTERN);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.TARGARYEN_PATTERN);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.STAG_PATTERN);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.ARRYN_PATTERN);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.ROSE_PATTERN);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.FISH_PATTERN);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.FALLEN_STAR_PATTERN);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.SWORD_PATTERN);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.ARROWS_PATTERN);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.WEIRWOOD_PATTERN);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.CARRIED_SHIELD_PATTERN);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.SEAHORSE_PATTERN);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.HIGHTOWER_PATTERN);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.BEACON_PATTERN);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.GRAPE_PATTERN);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.SCYTHE_PATTERN);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.BONEHAND_PATTERN);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.HORN_PATTERN);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.SEVEN_PATTERN);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.WYL_PATTERN);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.PRANCING_HORSE_PATTERN);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.HORSE_HEAD_PATTERN);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.CIRCLES_PATTERN);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.HOG_PATTERN);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.SHIELD_PATTERN);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.HUNTER_PATTERN);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.TWO_TOWERS_PATTERN);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.THREE_TOWERS_PATTERN);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.APPLE_PATTERN);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.HIVES_PATTERN);

        append(INGRIDIENTS_RESOURCE_KEY, ModItems.WEIRWOOD_STICK);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.BLACK_LEATHER);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.BLACK_WOOLEN_FABRIC);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.BLACK_STEEL_INGOT);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.BLACK_STEEL_NUGGET);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.BLACK_STEEL_LAMELLAR);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.BLACK_STEEL_SMALL_PLATE);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.BLACK_STEEL_PLATE);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.BLACK_STEEL_RING);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.BLACK_STEEL_CHAINMAIL);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.GILDED_STEEL_INGOT);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.GILDED_STEEL_NUGGET);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.GILDED_STEEL_SMALL_PLATE);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.GILDED_STEEL_PLATE);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.GILDED_STEEL_RING);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.GILDED_STEEL_CHAINMAIL);
        append(INGRIDIENTS_RESOURCE_KEY, ModItems.WHITENING_TEMPLATE);

        append(NATURAL_RESOURCE_KEY, ModItems.WEIRWOOD_SAPLING);
        append(NATURAL_RESOURCE_KEY, ModItems.WEIRWOOD_LOG_BLOCK);
        append(NATURAL_RESOURCE_KEY, ModItems.WEIRWOOD_FACE_GRIM_BLOCK);
        append(NATURAL_RESOURCE_KEY, ModItems.WEIRWOOD_FACE_HAPPY_BLOCK);
        append(NATURAL_RESOURCE_KEY, ModItems.WEIRWOOD_FACE_EASTER_EGG_BLOCK);
        append(NATURAL_RESOURCE_KEY, ModItems.WEIRWOOD_LEAVES_BLOCK);

        append(BUILDING_RESOURCE_KEY, ModItems.WEIRWOOD_LOG_BLOCK);
        append(BUILDING_RESOURCE_KEY, ModItems.WEIRWOOD_WOOD_BLOCK);
        append(BUILDING_RESOURCE_KEY, ModItems.STRIPPED_WEIRWOOD_LOG_BLOCK);
        append(BUILDING_RESOURCE_KEY, ModItems.STRIPPED_WEIRWOOD_WOOD_BLOCK);
        append(BUILDING_RESOURCE_KEY, ModItems.WEIRWOOD_PLANKS_BLOCK);
        append(BUILDING_RESOURCE_KEY, ModItems.WEIRWOOD_STAIRS_BLOCK);
        append(BUILDING_RESOURCE_KEY, ModItems.WEIRWOOD_SLAB_BLOCK);
        append(BUILDING_RESOURCE_KEY, ModItems.WEIRWOOD_FENCE_BLOCK);
        append(BUILDING_RESOURCE_KEY, ModItems.WEIRWOOD_FENCE_GATE_BLOCK);
        append(BUILDING_RESOURCE_KEY, ModItems.WEIRWOOD_DOOR_BLOCK);
        append(BUILDING_RESOURCE_KEY, ModItems.WEIRWOOD_TRAPDOOR_BLOCK);
        append(BUILDING_RESOURCE_KEY, ModItems.WEIRWOOD_PRESSURE_PLATE_BLOCK);
        append(BUILDING_RESOURCE_KEY, ModItems.WEIRWOOD_BUTTON_BLOCK);
        append(FUNC_RESOURCE_KEY, ModItems.WEIRWOOD_SIGN_BLOCK);
        append(FUNC_RESOURCE_KEY, ModItems.WEIRWOOD_HANGING_SIGN_BLOCK);
    }
    static Supplier<ItemStack> LANNISTER_CHESTPLATE_SUPPLIER
            = () -> ModItems.getDecoratedStack(ModItems.LANNISTER_CHESTPLATE, ModItems.LANNISTER_CAPE_DECORATION);
    static Supplier<ItemStack> LANNISTER_LORD_CHESTPLATE_SUPPLIER
            = () -> ModItems.getDecoratedStack(ModItems.LANNISTER_LORD_CHESTPLATE, ModItems.LANNISTER_CAPE_DECORATION);
}
