package net.ekotsk.item;

import com.magistuarmory.item.armor.ArmorType;
import dev.architectury.platform.Platform;
import net.ekotsk.ASOIAFMod;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvents;

public class ModArmorTypes {

    public static final ArmorType LANNISTER_HELMET = new ArmorType(new ResourceLocation(ASOIAFMod.MOD_ID, "lannister_helmet"), new ResourceLocation("ekotsk:lannister_helmet"), 0.5f, 0.0f, new Integer[] { 0, 0, 0, 240 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
    public static final ArmorType LANNISTER_LORD_HELMET = new ArmorType(new ResourceLocation(ASOIAFMod.MOD_ID, "lannister_lord_helmet"), new ResourceLocation("ekotsk:lannister_lord_helmet"), 1.3f, 0.5f, new Integer[] { 0, 0, 0, 275 }, new Integer[] { 0, 0, 0, 3 }, 10, SoundEvents.ARMOR_EQUIP_GOLD, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
    public static final ArmorType LANNISTER_CHESTPLATE = new ArmorType(new ResourceLocation(ASOIAFMod.MOD_ID, "lannister_chestplate"), new ResourceLocation("ekotsk:lannister_chestplate"), 0.5f, 0.0f, new Integer[] { 0, 0, 290, 0 }, new Integer[] { 0, 0, 6, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
    public static final ArmorType LANNISTER_LORD_CHESTPLATE = new ArmorType(new ResourceLocation(ASOIAFMod.MOD_ID, "lannister_lord_chestplate"), new ResourceLocation("ekotsk:lannister_lord_chestplate"), 1.3f, 0.5f, new Integer[] { 0, 0, 340, 0 }, new Integer[] { 0, 0, 8, 0 }, 10, SoundEvents.ARMOR_EQUIP_GOLD, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
    public static final ArmorType LANNISTER_LEGGINGS = new ArmorType(new ResourceLocation(ASOIAFMod.MOD_ID, "lannister_leggings"), new ResourceLocation("ekotsk:lannister_leggings"), 0.5f, 0.0f, new Integer[] { 0, 235, 0, 0 }, new Integer[] { 0, 5, 0, 0 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
    public static final ArmorType LANNISTER_LORD_LEGGINGS = new ArmorType(new ResourceLocation(ASOIAFMod.MOD_ID, "lannister_lord_leggings"), new ResourceLocation("ekotsk:lannister_lord_leggings"), 1.3f, 0.5f, new Integer[] { 0, 315, 0, 0 }, new Integer[] { 0, 5, 0, 0 }, 10, SoundEvents.ARMOR_EQUIP_GOLD, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
    public static final ArmorType FANCY_BOOTS = new ArmorType(new ResourceLocation(ASOIAFMod.MOD_ID, "fancy_boots"), new ResourceLocation("ekotsk:fancy_boots"), 0.0f, 0.0f, new Integer[] { 200, 0, 0, 0 }, new Integer[] { 2, 0, 0, 0 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, Platform.isForge() ? "forge:leather" : "c:leather");

    public static final ArmorType VALYRIAN_STEEL_HELMET = new ArmorType(new ResourceLocation(ASOIAFMod.MOD_ID, "valyrian_steel_helmet"), new ResourceLocation("ekotsk:valyrian_steel_helmet"), 4.0f, 0.3f, new Integer[] { 0, 0, 0, 5000 }, new Integer[] { 0, 0, 0, 4 }, 25, SoundEvents.ARMOR_EQUIP_NETHERITE, true, Platform.isForge() ? "forge:ingots/valyrian_steel" : "c:valyrian_steel_ingots");
    public static final ArmorType VALYRIAN_STEEL_ARMOR = new ArmorType(new ResourceLocation(ASOIAFMod.MOD_ID, "valyrian_steel_armor"), new ResourceLocation("ekotsk:valyrian_steel_armor"), 4.0f, 0.3f, new Integer[] { 5000, 7000, 10000, 0 }, new Integer[] { 4, 7, 9, 0 }, 25, SoundEvents.ARMOR_EQUIP_NETHERITE, true, Platform.isForge() ? "forge:ingots/valyrian_steel" : "c:valyrian_steel_ingots");

    public static final ArmorType HOTD_KINGSGUARD_ARMOR = new ArmorType(new ResourceLocation(ASOIAFMod.MOD_ID, "hotd_kingsguard_armor"), new ResourceLocation("ekotsk:hotd_kingsguard_armor"), 1.3f, 0.5f, new Integer[] { 235, 315, 340, 275 }, new Integer[] { 3, 5, 8, 3 }, 10, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
    public static final ArmorType KOTSK_KINGSGUARD_ARMOR = new ArmorType(new ResourceLocation(ASOIAFMod.MOD_ID, "kotsk_kingsguard_armor"), new ResourceLocation("ekotsk:kotsk_kingsguard_armor"), 1.3f, 0.5f, new Integer[] { 235, 315, 340, 275 }, new Integer[] { 3, 5, 8, 3 }, 10, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
    public static final ArmorType KINGSGUARD_ARMOR = new ArmorType(new ResourceLocation(ASOIAFMod.MOD_ID, "kingsguard_armor"), new ResourceLocation("ekotsk:kingsguard_armor"), 1.3f, 0.5f, new Integer[] { 235, 315, 340, 275 }, new Integer[] { 3, 5, 8, 3 }, 10, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
    public static final ArmorType KINGSGUARD_2_ARMOR = new ArmorType(new ResourceLocation(ASOIAFMod.MOD_ID, "kingsguard_2_armor"), new ResourceLocation("ekotsk:kingsguard_2_armor"), 1.3f, 0.5f, new Integer[] { 235, 315, 340, 275 }, new Integer[] { 3, 5, 8, 3 }, 10, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");

    public static final ArmorType GOLD_CLOAK_ARMOR = new ArmorType(new ResourceLocation(ASOIAFMod.MOD_ID, "gold_cloak_armor"), new ResourceLocation("ekotsk:gold_cloak_armor"), 0.5f, 0.1f, new Integer[] { 210, 300, 320, 250 }, new Integer[] { 2, 5, 7, 3 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/blacked_steel" : "c:blacked_steel_ingots");
    public static final ArmorType KOTSK_GOLD_CLOAK_ARMOR = new ArmorType(new ResourceLocation(ASOIAFMod.MOD_ID, "gold_cloak_armor_kotsk"), new ResourceLocation("ekotsk:gold_cloak_armor_kotsk"), 0.5f, 0.1f, new Integer[] { 150, 230, 250, 205 }, new Integer[] { 1, 4, 5, 2 }, 9, SoundEvents.ARMOR_EQUIP_CHAIN, true, Platform.isForge() ? "forge:ingots/gilded_steel" : "c:gilded_steel_ingots");
    public static final ArmorType GOT_GOLD_CLOAK_ARMOR = new ArmorType(new ResourceLocation(ASOIAFMod.MOD_ID, "gold_cloak_armor_got"), new ResourceLocation("ekotsk:gold_cloak_armor_got"), 0.5f, 0.1f, new Integer[] { 0, 235, 290, 240 }, new Integer[] { 0, 5, 6, 3 }, 9, SoundEvents.ARMOR_EQUIP_CHAIN, true, Platform.isForge() ? "forge:ingots/gilded_steel" : "c:gilded_steel_ingots");

    public static final ArmorType DORNISH_ARMOR = new ArmorType(new ResourceLocation(ASOIAFMod.MOD_ID, "dornish_armor"), new ResourceLocation("ekotsk:dornish_armor"), 0.5f, 0f, new Integer[] { 200, 235, 290, 240 }, new Integer[] { 3, 4, 6, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
    public static final ArmorType GREYJOY_ARMOR = new ArmorType(new ResourceLocation(ASOIAFMod.MOD_ID, "greyjoy_armor"), new ResourceLocation("ekotsk:greyjoy_armor"), 0.5f, 0f, new Integer[] { 200, 235, 290, 240 }, new Integer[] { 3, 4, 6, 2 }, 9, SoundEvents.ARMOR_EQUIP_CHAIN, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");
    public static final ArmorType NIGHT_WATCH_ARMOR = new ArmorType(new ResourceLocation(ASOIAFMod.MOD_ID, "night_watch_armor"), new ResourceLocation("ekotsk:night_watch_armor"), 0.5f, 0f, new Integer[] { 200, 235, 290, 240 }, new Integer[] { 3, 5, 6, 1 }, 8, SoundEvents.ARMOR_EQUIP_LEATHER, true, Platform.isForge() ? "forge:ingots/blacked_steel" : "c:blacked_steel_ingots");
    public static final ArmorType NORTHERN_ARMOR = new ArmorType(new ResourceLocation(ASOIAFMod.MOD_ID, "northern_armor"), new ResourceLocation("ekotsk:northern_armor"), 0.5f, 0f, new Integer[] { 200, 235, 290, 240 }, new Integer[] { 3, 5, 6, 2 }, 9, SoundEvents.ARMOR_EQUIP_IRON, true, Platform.isForge() ? "forge:ingots/steel" : "c:steel_ingots");


    public static final ArmorType HAND_SIGN = new ArmorType(new ResourceLocation(ASOIAFMod.MOD_ID, "hand_sign"), new ResourceLocation("ekotsk:hand_sign"), 0.0f, 0.0f, new Integer[] { 0, 0, 180, 0 }, new Integer[] { 0, 0, 1, 0 }, 9, SoundEvents.ARMOR_EQUIP_DIAMOND, true, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
    public static final ArmorType FANCY_CAPE = new ArmorType(new ResourceLocation(ASOIAFMod.MOD_ID, "cape"), new ResourceLocation("ekotsk:cape"), 0.0f, 0.0f, new Integer[] { 0, 0, 180, 0 }, new Integer[] { 0, 0, 0, 0 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
    public static final ArmorType NIGHT_WATCH_CAPE = new ArmorType(new ResourceLocation(ASOIAFMod.MOD_ID, "night_watch_cape"), new ResourceLocation("ekotsk:night_watch_cape"), 0.0f, 0.0f, new Integer[] { 0, 0, 180, 0 }, new Integer[] { 0, 0, 0, 0 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
    public static final ArmorType GOLD_CLOAK_LEFT = new ArmorType(new ResourceLocation(ASOIAFMod.MOD_ID, "gold_cloak_left"), new ResourceLocation("ekotsk:gold_cloak_left"), 0.0f, 0.0f, new Integer[] { 0, 0, 180, 0 }, new Integer[] { 0, 0, 0, 0 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");
    public static final ArmorType GOLD_CLOAK_RIGHT = new ArmorType(new ResourceLocation(ASOIAFMod.MOD_ID, "gold_cloak_right"), new ResourceLocation("ekotsk:gold_cloak_right"), 0.0f, 0.0f, new Integer[] { 0, 0, 180, 0 }, new Integer[] { 0, 0, 0, 0 }, 9, SoundEvents.ARMOR_EQUIP_LEATHER, true, Platform.isForge() ? "forge:ingots/bronze" : "c:bronze_ingots");

    public static final ArmorType AEGON_CROWN = new ArmorType(new ResourceLocation(ASOIAFMod.MOD_ID, "aegon_crown"), new ResourceLocation("ekotsk:aegon_crown"), 0.0f, 0.0f, new Integer[] { 0, 0, 0, 5000 }, new Integer[] { 0, 0, 0, 2 }, 9, SoundEvents.ARMOR_EQUIP_NETHERITE, true, Platform.isForge() ? "forge:ingots/valyrian_steel" : "c:valyrian_steel_ingots");

}
